// <auto-generated />
using System;
using Concertable.B2B.Deal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concertable.B2B.Deal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DealDbContext))]
    partial class DealDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deal")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DealEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Deals", "deal");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DoorSplitDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("numeric");

                    b.ToTable("DoorSplitDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.FlatFeeDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.ToTable("FlatFeeDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VenueHireDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("numeric");

                    b.ToTable("VenueHireDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VersusDealEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("numeric");

                    b.ToTable("VersusDeals", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DoorSplitDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.DoorSplitDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.FlatFeeDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.FlatFeeDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VenueHireDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.VenueHireDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VersusDealEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.VersusDealEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
