global using Concertable.Kernel;
global using Concertable.Kernel.Errors;
global using Concertable.Kernel.Functional;
global using Concertable.Kernel.ValueObjects;
global using Concertable.Contracts;
global using Concertable.Contracts.Enums;
global using Concertable.B2B.Artist.Domain.Entities;
global using Concertable.B2B.Artist.Domain.ReadModels;
global using Concertable.B2B.Artist.Contracts;
