// <auto-generated />
using System;
using System.Collections.Generic;
using Concertable.B2B.Concert.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concertable.B2B.Concert.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ConcertDbContext))]
    partial class ConcertDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("concert")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Artist.Domain.ReadModels.ArtistRatingProjection", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("ArtistId");

                    b.ToTable("ArtistRatingProjections", "artist", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CancellationOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DealType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Genres")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SettlementGrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("SettlementOperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("integer");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FinancialFailure", "Concertable.B2B.Concert.Domain.Entities.ConcertEntity.FinancialFailure#FinancialFailure", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FinancialFailureCode");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("FinancialFailureMessage");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "Concertable.B2B.Concert.Domain.Entities.ConcertEntity.Period#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartDate");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SettlementPaymentReference", "Concertable.B2B.Concert.Domain.Entities.ConcertEntity.SettlementPaymentReference#PaymentOperationReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClientReference")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("OperationType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CancellationOperationId")
                        .IsUnique()
                        .HasFilter("\"CancellationOperationId\" IS NOT NULL");

                    b.HasIndex("SettlementOperationId")
                        .IsUnique()
                        .HasFilter("\"SettlementOperationId\" IS NOT NULL");

                    b.HasIndex("VenueId");

                    b.ToTable("Concerts", "concert");

                    b.HasDiscriminator<int>("DealType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertImages", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.InvoiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DealType")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PdfBlobName")
                        .HasColumnType("text");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TaxPointUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amounts", "Concertable.B2B.Concert.Domain.Entities.InvoiceEntity.Amounts#VatBreakdown", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Gross")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Net")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)");

                            b1.Property<decimal>("Vat")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Customer", "Concertable.B2B.Concert.Domain.Entities.InvoiceEntity.Customer#InvoiceParty", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Supplier", "Concertable.B2B.Concert.Domain.Entities.InvoiceEntity.Supplier#InvoiceParty", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.InvoiceSequenceEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId");

                    b.ToTable("InvoiceSequences", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.SelfBillingAgreementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClauseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PdfBlobName")
                        .HasColumnType("text");

                    b.Property<string>("PlatformTermsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Supplier", "Concertable.B2B.Concert.Domain.Entities.SelfBillingAgreementEntity.Supplier#InvoiceParty", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SupplierESignature", "Concertable.B2B.Concert.Domain.Entities.SelfBillingAgreementEntity.SupplierESignature#ESignature", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DrawnSignatureImage")
                                .HasColumnType("text");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)");

                            b1.Property<string>("SignatoryName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");
                        });

                    b.HasKey("Id");

                    b.ToTable("SelfBillingAgreements", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("ArtistReadModels", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModelGenre", b =>
                {
                    b.Property<int>("ArtistReadModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.HasKey("ArtistReadModelId", "Genre");

                    b.ToTable("ArtistReadModelGenres", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ConcertRatingProjection", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("ConcertId");

                    b.ToTable("ConcertRatingProjections", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.VenueReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("VenueReadModels", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Venue.Domain.ReadModels.VenueRatingProjection", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("VenueId");

                    b.ToTable("VenueRatingProjections", "venue", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.DoorSplitConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DoorRevenue")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.FlatFeeConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.VenueHireConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.VersusConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DoorRevenue")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("numeric");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.B2B.Concert.Domain.ReadModels.VenueReadModel", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertImageEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", "Concert")
                        .WithMany("Images")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ArtistReadModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Town");

                            b1.HasKey("ArtistReadModelId");

                            b1.ToTable("ArtistReadModels", "concert");

                            b1.WithOwner()
                                .HasForeignKey("ArtistReadModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModelGenre", b =>
                {
                    b.HasOne("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", "Artist")
                        .WithMany("Genres")
                        .HasForeignKey("ArtistReadModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.VenueReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("VenueReadModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Town");

                            b1.HasKey("VenueReadModelId");

                            b1.ToTable("VenueReadModels", "concert");

                            b1.WithOwner()
                                .HasForeignKey("VenueReadModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
