/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessRouteRouteImport } from './routes/_business/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as BusinessAppRouteImport } from './routes/_business/app'
import { Route as BusinessSettingsRouteRouteImport } from './routes/_business/settings/route'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BusinessConcertIdRouteImport } from './routes/_business/concert/$id'
import { Route as BusinessSettingsIndexRouteImport } from './routes/_business/settings/index'
import { Route as BusinessSettingsMembersRouteImport } from './routes/_business/settings/members'
import { Route as BusinessSettingsOrganizationRouteImport } from './routes/_business/settings/organization'
import { Route as SettingsMembersAcceptInvitationIdRouteImport } from './routes/settings/members/accept.$invitationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRouteRoute = BusinessRouteRouteImport.update({
  id: '/_business',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAppRoute = BusinessAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessSettingsRouteRoute = BusinessSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessConcertIdRoute = BusinessConcertIdRouteImport.update({
  id: '/concert/$id',
  path: '/concert/$id',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const BusinessSettingsIndexRoute = BusinessSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessSettingsRouteRoute,
} as any)
const BusinessSettingsMembersRoute = BusinessSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => BusinessSettingsRouteRoute,
} as any)
const BusinessSettingsOrganizationRoute =
  BusinessSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => BusinessSettingsRouteRoute,
  } as any)
const SettingsMembersAcceptInvitationIdRoute =
  SettingsMembersAcceptInvitationIdRouteImport.update({
    id: '/settings/members/accept/$invitationId',
    path: '/settings/members/accept/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof BusinessSettingsRouteRouteWithChildren
  '/app': typeof BusinessAppRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/concert/$id': typeof BusinessConcertIdRoute
  '/settings/members': typeof BusinessSettingsMembersRoute
  '/settings/organization': typeof BusinessSettingsOrganizationRoute
  '/settings/': typeof BusinessSettingsIndexRoute
  '/settings/members/accept/$invitationId': typeof SettingsMembersAcceptInvitationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof BusinessAppRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/concert/$id': typeof BusinessConcertIdRoute
  '/settings/members': typeof BusinessSettingsMembersRoute
  '/settings/organization': typeof BusinessSettingsOrganizationRoute
  '/settings': typeof BusinessSettingsIndexRoute
  '/settings/members/accept/$invitationId': typeof SettingsMembersAcceptInvitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_business': typeof BusinessRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_business/settings': typeof BusinessSettingsRouteRouteWithChildren
  '/_business/app': typeof BusinessAppRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_business/concert/$id': typeof BusinessConcertIdRoute
  '/_business/settings/members': typeof BusinessSettingsMembersRoute
  '/_business/settings/organization': typeof BusinessSettingsOrganizationRoute
  '/_business/settings/': typeof BusinessSettingsIndexRoute
  '/settings/members/accept/$invitationId': typeof SettingsMembersAcceptInvitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/app'
    | '/auth/callback'
    | '/concert/$id'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/'
    | '/settings/members/accept/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/auth/callback'
    | '/concert/$id'
    | '/settings/members'
    | '/settings/organization'
    | '/settings'
    | '/settings/members/accept/$invitationId'
  id:
    | '__root__'
    | '/'
    | '/_business'
    | '/login'
    | '/register'
    | '/_business/settings'
    | '/_business/app'
    | '/auth/callback'
    | '/_business/concert/$id'
    | '/_business/settings/members'
    | '/_business/settings/organization'
    | '/_business/settings/'
    | '/settings/members/accept/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRouteRoute: typeof BusinessRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SettingsMembersAcceptInvitationIdRoute: typeof SettingsMembersAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_business': {
      id: '/_business'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BusinessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_business/app': {
      id: '/_business/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof BusinessAppRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/_business/settings': {
      id: '/_business/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof BusinessSettingsRouteRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_business/concert/$id': {
      id: '/_business/concert/$id'
      path: '/concert/$id'
      fullPath: '/concert/$id'
      preLoaderRoute: typeof BusinessConcertIdRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/_business/settings/': {
      id: '/_business/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof BusinessSettingsIndexRouteImport
      parentRoute: typeof BusinessSettingsRouteRoute
    }
    '/_business/settings/members': {
      id: '/_business/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof BusinessSettingsMembersRouteImport
      parentRoute: typeof BusinessSettingsRouteRoute
    }
    '/_business/settings/organization': {
      id: '/_business/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof BusinessSettingsOrganizationRouteImport
      parentRoute: typeof BusinessSettingsRouteRoute
    }
    '/settings/members/accept/$invitationId': {
      id: '/settings/members/accept/$invitationId'
      path: '/settings/members/accept/$invitationId'
      fullPath: '/settings/members/accept/$invitationId'
      preLoaderRoute: typeof SettingsMembersAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusinessSettingsRouteRouteChildren {
  BusinessSettingsMembersRoute: typeof BusinessSettingsMembersRoute
  BusinessSettingsOrganizationRoute: typeof BusinessSettingsOrganizationRoute
  BusinessSettingsIndexRoute: typeof BusinessSettingsIndexRoute
}

const BusinessSettingsRouteRouteChildren: BusinessSettingsRouteRouteChildren = {
  BusinessSettingsMembersRoute: BusinessSettingsMembersRoute,
  BusinessSettingsOrganizationRoute: BusinessSettingsOrganizationRoute,
  BusinessSettingsIndexRoute: BusinessSettingsIndexRoute,
}

const BusinessSettingsRouteRouteWithChildren =
  BusinessSettingsRouteRoute._addFileChildren(
    BusinessSettingsRouteRouteChildren,
  )

interface BusinessRouteRouteChildren {
  BusinessSettingsRouteRoute: typeof BusinessSettingsRouteRouteWithChildren
  BusinessAppRoute: typeof BusinessAppRoute
  BusinessConcertIdRoute: typeof BusinessConcertIdRoute
}

const BusinessRouteRouteChildren: BusinessRouteRouteChildren = {
  BusinessSettingsRouteRoute: BusinessSettingsRouteRouteWithChildren,
  BusinessAppRoute: BusinessAppRoute,
  BusinessConcertIdRoute: BusinessConcertIdRoute,
}

const BusinessRouteRouteWithChildren = BusinessRouteRoute._addFileChildren(
  BusinessRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRouteRoute: BusinessRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SettingsMembersAcceptInvitationIdRoute:
    SettingsMembersAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
