// <auto-generated />
using System;
using System.Collections.Generic;
using Concertable.B2B.Application.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.B2B.Application.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916112137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("application")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ApplicationAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Facet")
                        .HasColumnType("int");

                    b.Property<Guid>("IssuedByTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IssuedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "TenantId", "Facet")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationAccessGrants_TenantWide")
                        .HasFilter("[RevokedAt] IS NULL AND [MemberUserId] IS NULL");

                    b.HasIndex("ResourceId", "TenantId", "Facet", "MemberUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationAccessGrants_Member")
                        .HasFilter("[RevokedAt] IS NULL AND [MemberUserId] IS NOT NULL");

                    b.HasIndex("TenantId", "Facet", "ResourceId", "MemberUserId")
                        .HasFilter("[RevokedAt] IS NULL");

                    b.ToTable("ApplicationAccessGrants", "application");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AcceptanceOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DealType")
                        .HasColumnType("int");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("TermsFingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArtistESignature", "Concertable.B2B.Application.Domain.Entities.ApplicationEntity.ArtistESignature#ContractSignature", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DrawnSignatureImage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)");

                            b1.Property<string>("SignatoryName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceOperationId")
                        .IsUnique()
                        .HasFilter("[AcceptanceOperationId] IS NOT NULL");

                    b.HasIndex("OpportunityId")
                        .IsUnique()
                        .HasFilter("[State] = 1");

                    b.HasIndex("OpportunityId", "ArtistId")
                        .IsUnique();

                    b.ToTable("Applications", "application");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ConcertAvailabilityEntity", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("ConcertId");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.HasIndex("ArtistId", "StartDate");

                    b.HasIndex("VenueId", "StartDate");

                    b.ToTable("ConcertAvailabilities", "application");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("VerifyPayments", "application");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VerifyPaymentEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.B2B.DataAccess.Application.MembershipAuthorityFact", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AuthorizationVersion")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "UserId");

                    b.ToTable("Memberships", "tenant", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.FailedVerifyPaymentEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FailedVerifyPaymentEntity");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.SucceededVerifyPaymentEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity");

                    b.HasDiscriminator().HasValue("SucceededVerifyPaymentEntity");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ApplicationAccessGrant", b =>
                {
                    b.HasOne("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", null)
                        .WithMany("AccessGrants")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", null)
                        .WithOne("VerifyPayment")
                        .HasForeignKey("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("AccessGrants");

                    b.Navigation("VerifyPayment");
                });
#pragma warning restore 612, 618
        }
    }
}
