// <auto-generated />
using System;
using System.Collections.Generic;
using Concertable.B2B.Application.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concertable.B2B.Application.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("application")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AcceptanceOperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("DealType")
                        .HasColumnType("integer");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("TermsFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArtistESignature", "Concertable.B2B.Application.Domain.Entities.ApplicationEntity.ArtistESignature#ContractSignature", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DrawnSignatureImage")
                                .HasColumnType("text");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)");

                            b1.Property<string>("SignatoryName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceOperationId")
                        .IsUnique()
                        .HasFilter("\"AcceptanceOperationId\" IS NOT NULL");

                    b.HasIndex("OpportunityId")
                        .IsUnique()
                        .HasFilter("\"State\" = 1");

                    b.HasIndex("OpportunityId", "ArtistId")
                        .IsUnique();

                    b.ToTable("Applications", "application");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ConcertAvailabilityEntity", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uuid");

                    b.HasKey("ConcertId");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.HasIndex("ArtistId", "StartDate");

                    b.HasIndex("VenueId", "StartDate");

                    b.ToTable("ConcertAvailabilities", "application");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("VerifyPayments", "application");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VerifyPaymentEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.FailedVerifyPaymentEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("FailedVerifyPaymentEntity");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.SucceededVerifyPaymentEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity");

                    b.HasDiscriminator().HasValue("SucceededVerifyPaymentEntity");
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", null)
                        .WithOne("VerifyPayment")
                        .HasForeignKey("Concertable.B2B.Application.Domain.Entities.VerifyPaymentEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Application.Domain.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("VerifyPayment");
                });
#pragma warning restore 612, 618
        }
    }
}
