// <auto-generated />
using System;
using System.Collections.Generic;
using Concertable.B2B.Booking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.B2B.Booking.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260828153020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Booking.Domain.Entities.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CancellationOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DealType")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedFinancialOperation")
                        .HasColumnType("int");

                    b.Property<string>("FinancialFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FinancialFailureMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FinancialOperationReferenceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDoorRevenue")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("CancellationOperationId")
                        .IsUnique()
                        .HasFilter("[CancellationOperationId] IS NOT NULL");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("Bookings", "booking");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BookingEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.B2B.Booking.Domain.Entities.ContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PdfBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformTermsVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArtistSignature", "Concertable.B2B.Booking.Domain.Entities.ContractEntity.ArtistSignature#Signature", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DrawnSignatureImage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)");

                            b1.Property<string>("SignatoryName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "Concertable.B2B.Booking.Domain.Entities.ContractEntity.Period#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("Period_End");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("Period_Start");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "VenueSignature", "Concertable.B2B.Booking.Domain.Entities.ContractEntity.VenueSignature#Signature", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DrawnSignatureImage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)");

                            b1.Property<string>("SignatoryName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Contracts", "booking");
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Booking.Domain.Entities.DeferredBooking", b =>
                {
                    b.HasBaseType("Concertable.B2B.Booking.Domain.Entities.BookingEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("DeferredBooking");
                });

            modelBuilder.Entity("Concertable.B2B.Booking.Domain.Entities.StandardBooking", b =>
                {
                    b.HasBaseType("Concertable.B2B.Booking.Domain.Entities.BookingEntity");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("StandardBooking");
                });

            modelBuilder.Entity("Concertable.B2B.Booking.Domain.Entities.ContractEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Booking.Domain.Entities.BookingEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Booking.Domain.Entities.ContractEntity", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
