global using Concertable.Kernel;
global using Concertable.Kernel.Errors;
global using Concertable.Kernel.Functional;
global using Concertable.Kernel.ValueObjects;
global using Concertable.Contracts;
global using Concertable.Contracts.Enums;
global using Concertable.B2B.Deal.Contracts;
global using Concertable.B2B.Deal.Contracts.Enums;
global using Concertable.B2B.Concert.Domain.ValueObjects;
